In [2]:
import torch
import numpy as np

## Tensor to Array

In [2]:
# Example 1 - Transform tensors and arrays
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [4]:
# Example 2 - Transform tensors and arrays integers
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


## Tensor Addition

In [5]:
# Example 3 - Tensor Addition
a = torch.randn((2,3))
b = torch.randn(3)
print(a.shape, b.shape)
print(a, b)
t_add1 = a + b
t_add2 = torch.add(a,b)
print(t_add1.shape, t_add2.shape)
print(t_add1, t_add2)

torch.Size([2, 3]) torch.Size([3])
tensor([[ 0.4055,  0.5707, -0.1432],
        [-2.5610, -0.8068, -0.3008]]) tensor([-0.4524, -0.7087,  0.7100])
torch.Size([2, 3]) torch.Size([2, 3])
tensor([[-0.0469, -0.1380,  0.5668],
        [-3.0134, -1.5155,  0.4092]]) tensor([[-0.0469, -0.1380,  0.5668],
        [-3.0134, -1.5155,  0.4092]])


## Tensor Multiplication

In [7]:
# Example 4 - Tensor Multiplication
t_mul1 = a * b
t_mul2 = torch.mul(a, b)
print(t_mul1.shape, t_mul2.shape)
print(t_mul1, t_mul2)

torch.Size([2, 3]) torch.Size([2, 3])
tensor([[-0.1834, -0.4045, -0.1017],
        [ 1.1586,  0.5718, -0.2136]]) tensor([[-0.1834, -0.4045, -0.1017],
        [ 1.1586,  0.5718, -0.2136]])


## Tensor Reshape

In [3]:
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],[[5, 6, 7], [7, 8, 9]]])
print(a.shape)
b = a.reshape(2, 6)
c = a.view(2, 6)
d = a.reshape(2, -1) ##flatten to [2,12/6]
print(b.shape, c.shape, d.shape)
print(b,c,d)

torch.Size([2, 2, 3])
torch.Size([2, 6]) torch.Size([2, 6]) torch.Size([2, 6])
tensor([[1, 2, 3, 3, 4, 5],
        [5, 6, 7, 7, 8, 9]]) tensor([[1, 2, 3, 3, 4, 5],
        [5, 6, 7, 7, 8, 9]]) tensor([[1, 2, 3, 3, 4, 5],
        [5, 6, 7, 7, 8, 9]])


## Change Dimensions

In [4]:
#expand dimension
g = torch.unsqueeze(a, dim=1) 
#squeeze dimension
h = torch.squeeze(g) 
print(g.shape, h.shape)

torch.Size([2, 1, 2, 3]) torch.Size([2, 2, 3])
